apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: virtualserviceconfigs.extension.networking.istio.io
spec:
  group: extension.networking.istio.io
  names:
    kind: VirtualServiceConfig
    listKind: VirtualServiceConfigList
    plural: virtualserviceconfigs
    shortNames:
    - vsc
    singular: virtualserviceconfig
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: This is the VirtualServiceConfigStatus Description
            properties:
              status:
                type: string
            type: object
          spec:
            description: This is the VirtualServiceConfigSpec Description
            properties:
              virtualServiceName:
                type: string
              host:
                type: string
              http:
                items:
                  properties:
                    name:
                      nullable: true
                      type: string
                    order:
                      format: int32
                      type: integer
                    match:
                      properties:
                        name:
                          nullable: true
                          type: string
                        uri:
                          properties:
                            exact:
                              type: string
                            prefix:
                              type: string
                            regex:
                              type: string
                          type: object
                        headers:
                          additionalProperties:
                            properties:
                              exact:
                                type: string
                              prefix:
                                type: string
                              regex:
                                type: string
                            type: object
                          type: object
                      type: object
                    route:
                      properties:
                        host:
                          type: string
                        subset:
                          type: string
                      type: object
                  type: object
                type: array
            required:
            - virtualServiceName
            - host
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
