apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: virtualserviceconfigs.extension.networking.istio.io
spec:
  group: extension.networking.istio.io
  names:
    kind: VirtualServiceConfig
    listKind: VirtualServiceConfigList
    plural: virtualserviceconfigs
    singular: virtualserviceconfig
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties:
              status:
                type: string
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              host:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
