apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
- apiGroups:
  - extension.networking.istio.io
  - coordination.k8s.io
  resources:
  - virtualserviceconfigs
  - leases
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
- apiGroups:
  - extension.networking.istio.io
  resources:
  - virtualserviceconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
